version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/twitter_openapi_dart/example/flutter_example"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/twitter_openapi_dart"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/twitter_openapi_dart_generated"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
