openapi: 3.0.3
info:
  title: Twitter OpenAPI
  version: 0.0.1

paths:
  /{{HomeTimelineQuery}}/HomeTimeline:
    get:
      operationId: getHomeTimeline
      description: get tweet list of timeline
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimelineResponse"
      tags:
        - "timeline"
        - "login-required"
        - "graphql"

  /{{HomeLatestTimelineQuery}}/HomeLatestTimeline:
    get:
      operationId: getHomeLatestTimeline
      description: get tweet list of timeline
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimelineResponse"
      tags:
        - "timeline"
        - "login-required"
        - "graphql"

  /{{ListLatestTweetsTimelineQuery}}/ListLatestTweetsTimeline:
    get:
      operationId: getListLatestTweetsTimeline
      description: get tweet list of timeline
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListTweetsTimelineResponse"
      tags:
        - "timeline"
        - "login-required"
        - "graphql"

components:
  schemas:
    TimelineResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/HomeTimelineResponseData"

    HomeTimelineResponseData:
      required:
        - "home"
      properties:
        home:
          $ref: "#/components/schemas/HomeTimelineHome"

    HomeTimelineHome:
      required:
        - "home_timeline_urt"
      properties:
        home_timeline_urt:
          $ref: "./../schemas/timeline.yaml#/components/schemas/Timeline"

    ListTweetsTimelineResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/ListTweetsTimelineData"

    ListTweetsTimelineData:
      required:
        - "list"
      properties:
        list:
          $ref: "#/components/schemas/ListTweetsTimelineList"

    ListTweetsTimelineList:
      required:
        - "tweets_timeline"
      properties:
        tweets_timeline:
          $ref: "#/components/schemas/ListTweetsTimeline"

    ListTweetsTimeline:
      required:
        - "timeline"
      properties:
        timeline:
          $ref: "./../schemas/timeline.yaml#/components/schemas/Timeline"
