inputSpec: twitter-openapi/dist/compatible_discriminator/openapi-3.0.yaml
outputDir: .

pubName: twitter_openapi_dart_generated
pubDescription: Twitter OpenAPI Dart
pubVersion: 0.0.10
pubAuthor: fa0311

pubHomepage: https://github.com/fa0311/twitter_openapi_dart
