name: twitter_openapi_dart
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/fa0311/twitter_openapi_dart

publish_to: "none"

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  # path: ^1.8.0

  intl: ^0.18.1
  cookie_jar: ^3.0.1

  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  # twitter_openapi_dart_generated:
  #   path: ../twitter_openapi_dart_generated
  twitter_openapi_dart_generated:
    git:
      url: https://github.com/fa0311/twitter_openapi_dart.git
      path: twitter_openapi_dart_generated
      tag: "v0.0.1"

  # flutter_inappwebview: ^5.7.2+3
  collection: ^1.17.0
  built_value: ">=8.4.0 <9.0.0"
  built_collection: ">=5.1.1 <6.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

  built_value_generator: ">=8.4.0 <9.0.0"
  build_runner: any

assets:
  - twitter-openapi/src/config/placeholder.json
