name: flutter_example
description: A new Flutter project.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  twitter_openapi_dart: ^0.0.6
  flutter_inappwebview: ^5.7.2+3
  collection: ^1.17.0
  dio: "^5.0.0"
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
