openapi: 3.0.3
info:
  title: Twitter OpenAPI
  version: 0.0.1

paths:
  /{{TweetDetailQuery}}/TweetDetail:
    get:
      operationId: getTweetDetail
      description: get TweetDetail
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TweetDetailResponse"
      tags:
        - "bookmark"
        - "graphql"

components:
  schemas:
    TweetDetailResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/BookmarksResponseData"

    BookmarksResponseData:
      required:
        - "threaded_conversation_with_injections_v2"
      properties:
        threaded_conversation_with_injections_v2:
          $ref: "./../schemas/timeline.yaml#/components/schemas/Timeline"
