inputSpec: twitter-openapi/dist/openapi-3.0.yaml
outputDir: .
additionalProperties:
  pubName: twitter_openapi_dart
  pubDescription: Twitter OpenAPI Dart
  pubVersion: 0.0.1
  pubAuthor: yuki
  pubHomepage: https://github.com/vrchatapi/vrchatapi-dart
